spring.application.name=musicshop

spring.datasource.url=jdbc:postgresql://db:5432/musicshop
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
# You might need to adjust the naming strategy for PostgreSQL if you encounter issues
# spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
# spring.jpa.hibernate.naming.physical-strategy=net.digitalbooster.musicshop.config.JpaConfig$1